#!/bin/bash
# Xibalba AI Setup Script
# Configures local Xibalba AI connection for VectorForge

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║     Xibalba AI Configuration Setup                       ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""

# Check for Xibalba directory
XIBALBA_DIR="$HOME/.xibalba"
if [ ! -d "$XIBALBA_DIR" ]; then
    echo "⚠️  Xibalba directory not found at $XIBALBA_DIR"
    echo "   Creating default configuration..."
    mkdir -p "$XIBALBA_DIR"
fi

# Check for MCP server
echo "🔍 Checking for MCP server..."
MCP_PORT=8000
if command -v curl &> /dev/null; then
    if curl -s "http://localhost:$MCP_PORT/health" > /dev/null 2>&1; then
        echo "✓ MCP server detected on port $MCP_PORT"
    else
        echo "⚠️  MCP server not responding on port $MCP_PORT"
        echo "   Make sure your Xibalba MCP server is running"
    fi
else
    echo "⚠️  curl not found, skipping MCP server check"
fi

# Create/update .env.local
ENV_FILE="$PROJECT_DIR/.env.local"
echo "📝 Configuring environment..."

# Detect Xibalba API key from common locations
XIBALBA_KEY=""
if [ -f "$HOME/.xibalba/api_key" ]; then
    XIBALBA_KEY=$(cat "$HOME/.xibalba/api_key" | tr -d '\n')
elif [ -f "$HOME/.config/xibalba/api_key" ]; then
    XIBALBA_KEY=$(cat "$HOME/.config/xibalba/api_key" | tr -d '\n')
fi

cat > "$ENV_FILE" << EOF
# Xibalba AI Configuration
# Auto-generated by setup script

VITE_XIBALBA_MCP_URL=http://localhost:8000
VITE_XIBALBA_API_KEY=${XIBALBA_KEY}
VITE_XIBALBA_MODEL=xibalba-local
VITE_XIBALBA_ENDPOINT=/api/v1/chat/completions

# MCP Configuration
# If your MCP server runs on a different port, update MCP_URL above
# Default: http://localhost:8000
EOF

echo "✓ Created/updated .env.local"

# Create local config in browser storage format
LOCAL_CONFIG='{
  "mcpServerUrl": "http://localhost:8000",
  "apiKey": "'"${XIBALBA_KEY}"'",
  "model": "xibalba-local",
  "endpoint": "/api/v1/chat/completions"
}'

echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║              Configuration Complete!                     ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "📋 Configuration saved to: $ENV_FILE"
echo ""
echo "🔧 To manually configure:"
echo "   1. Edit $ENV_FILE"
echo "   2. Set VITE_XIBALBA_MCP_URL to your MCP server URL"
echo "   3. Set VITE_XIBALBA_API_KEY if required"
echo ""
echo "🚀 Start VectorForge:"
echo "   npm run dev"
echo ""
echo "💡 The app will use localStorage config if .env.local is not available"
echo "   This makes it fully portable for USB deployment!"
echo ""

